### ISSUE TITLE
Publish 0.10.0 on NPM

### ISSUE THREAD

**Issue by andys8** [stil4m/elm-analyse#100]
I don't want to rush at all, but the new release is missing on NPM and I'm very curious.
@stil4m In case you forgot to publish it, let this be your reminder :)

![image](https://user-images.githubusercontent.com/13085980/28961573-101fa188-7903-11e7-8cc7-75bd3e9a2689.png)
![image](https://user-images.githubusercontent.com/13085980/28961584-204fd7e4-7903-11e7-8996-08cd162ea84d.png)

**Comment by stil4m** [comment]
Yep. I screwed up. Thanks for pointing that out! You are a hero.

It should be up now.

**Comment by andys8** [comment]
Awesome, thanks :+1:
