### ISSUE TITLE
[Improvement] LineLengthExceeded could display lines

### ISSUE THREAD

**Issue by andys8** [stil4m/elm-analyse#103]
I've a minor suggestion for the output message of `LineLengthExceeded`: Line numbers would be awesome :smiley: It works as it is for small files but it takes quite a while in large `Main` files.

```sh
Line length exceeded on 1 line(s) in file "src/Main.elm".
```

### Source
https://github.com/stil4m/elm-analyse/blob/master/src/Analyser/Messages/Util.elm#L467-L478

I think for duplicates it's already implemented to print range**s**:
https://github.com/stil4m/elm-analyse/blob/master/src/Analyser/Messages/Util.elm#L315-L345

**Comment by stil4m** [comment]
Good point. I use `elm-analyse` mostly as UI (`elm-analyse -s`) and then I do not encounter this issue. I must keep a broader mind when I implement these things. 🤐

**Comment by stil4m** [comment]
@andys8 What about something like this:

```
Line length exceeded on line(s) [12,30] in file "docs/Docs/Configuration.elm".
Line length exceeded on line(s) [33,36,46,61,89,99,102,107] in file "docs/Docs/Features.elm".
Line length exceeded on line(s) [55,80,101] in file "docs/Docs/Home.elm".
Line length exceeded on line(s) [123,168,190,797] in file "docs/Docs/MsgDoc.elm".
```

**Comment by andys8** [comment]
Awesome :smiley:
