### ISSUE TITLE
README: All supported checks should be listed

### ISSUE THREAD

**Issue by andys8** [stil4m/elm-analyse#104]
The [README.md](https://github.com/stil4m/elm-analyse/blob/master/README.md) is listing 23 checks. 
There are 25 files (ignoring `Base.elm`) in [Analyser/Checks](https://github.com/stil4m/elm-analyse/tree/master/src/Analyser/Checks). Some of them like `NoDebug.elm` are implementing multiple rules.

I'm creating this issue to start collecting differences between the list in the documentation and the implementation.

**Comment by andys8** [comment]
### Checks in code

CoreArrayUsage
DebugCrash
DebugLog
DropConcatOfLists
DropConsOfItemAndList
DuplicateImport
DuplicateImportedVariable
DuplicateRecordFieldUpdate
ExposeAll
FunctionInLet
ImportAll
LineLengthExceeded
MultiLineRecordFormatting
NoTopLevelSignature
NoUncurriedPrefix
NonStaticRegex
RedefineVariable
SingleFieldRecord
TriggerWords
UnformattedFile
UnnecessaryListConcat
UnnecessaryParens
UnnecessaryPortModule
UnusedImport
UnusedImportAlias
UnusedImportedVariable
UnusedPatternVariable
UnusedTopLevel
UnusedTypeAlias
UnusedVariable
UseConsOverConcat

### Checks in README.md

DebugCrash
DebugLog
DropConcatOfLists
DropConsOfItemAndList
DuplicateImport
ExposeAll
ImportAll
LineLengthExceeded
MultiLineRecordFormatting
NoTopLevelSignature
NoUncurriedPrefix
RedefineVariable
UnformattedFile
UnnecessaryListConcat
UnnecessaryParens
UnusedImport
UnusedImportAlias
UnusedImportedVariable
UnusedPatternVariable
UnusedTopLevel
UnusedTypeAlias
UnusedVariable
UseConsOverConcat

### Diff

CoreArrayUsage
DuplicateImportedVariable
DuplicateRecordFieldUpdate
FunctionInLet
NonStaticRegex
SingleFieldRecord
TriggerWords
UnnecessaryPortModule

**Comment by stil4m** [comment]
Yeah. My bad. I've started a [docs page](https://stil4m.github.io/elm-analyse). This is currently the truth. It also contains a list of [checks](https://stil4m.github.io/elm-analyse/#/messages).

**Comment by stil4m** [comment]
I've to update the readme once I get some coding time.

**Comment by andys8** [comment]
Cool, didn't know that. Do you plan to keep the README in sync or remove it and link to the page?

**Comment by stil4m** [comment]
Fixed in next release.
