### ISSUE TITLE
Idea: Detect Unused Packages

### ISSUE THREAD

**Issue by rtfeldman** [stil4m/elm-analyse#107]
We use around 50 packages at work, and if we ever refactored our way into no longer using one of them, we'd probably never realize it!

Would be sweet if `elm-analyse` could detect this and let us know!

**Comment by stil4m** [comment]
Great idea. I've been thinking about clone detection, but lifting this across the libraries may be an awesome idea. In addition, the educational aspect would be helpful: "I'm writing this function, but somebody else has already written it for me".

**Comment by stil4m** [comment]
In the patch I made, the  human-readable console output will include the following snippet if you have unused dependencies:

```
Unused dependencies:
- stil4m/elm-aui-css
...
```

The JSON-formatted output contains a list of strings with the key `unusedDependencies` with all the names of the packages that are not used by the target elm project.
`elm-analyse` will exit with a non-zero code when there are unused dependencies.
The web GUI has a new page listing unused dependencies (this page will be expanded later with additional dependency related information).
