### ISSUE TITLE
Graph rendering fails if code base contains a duplicate import

### ISSUE THREAD

**Issue by pietro909** [stil4m/elm-analyse#112]
I can't see the Graph (it is not rendered).

The console says:

`Uncaught The edge "Api-Api<->Models" already exists.`

*Api* and *Models* are two of my modules.

**Comment by stil4m** [comment]
That is not good. Could you provide which version of `elm-analyse` you are using? Would it be possible to create a reproducible example? Thanks

**Comment by pietro909** [comment]
- version is `0.11.0`
- it is installed locally (I run it with `./node_modules/.bin/elm-analyse"`)
- elm version is 0.18

For the example, I need to work on this a bit because the codebase is closed source.

Thank you for your prompt reply, and for this amazing tool!

**Comment by pietro909** [comment]
I've sorted it out: when an import is *duplicated*, it generates the error.

For instance:
```
import Helpers
import Helpers exposing (aHelper)
```

Removing the second import works. I've prepared a [self-contained minimum example here](https://github.com/pietro909/elm-playground/tree/master/elm-analyse-duplicated-import).

**Comment by stil4m** [comment]
Good to know that you have found the cause. I'll rename the issue and pick that up in the next release.

**Comment by stil4m** [comment]
Fixed with #101. This is currently replaced with a DOT file which fixes this issue.
