### ISSUE TITLE
Case where error messaging is inappropriate.

### ISSUE THREAD

**Issue by mbuscemi** [stil4m/elm-analyse#113]
I am getting the error: 

> Record has only one field, you can simply this. In file "src/State/Failure.elm"

On this:

`type alias Reason =
    { data : Comparison
    }`

In this case, I really can't simplify (at least not without breaking my type model of the JSON), as this is a layer within a set of nested JSON decoders, and I don't have control of the JSON structure. It's entering my Elm app from a third-party service via a port.

More:
```
type alias Comparison =
    { comparison : String
    , actual : Maybe String
    , expected : Maybe String
    , first : Maybe String
    , second : Maybe String
    }


comparison : Decoder Comparison
comparison =
    map5 Comparison
        (field "comparison" string)
        (maybe (field "actual" string))
        (maybe (field "expected" string))
        (maybe (field "first" string))
        (maybe (field "second" string))


type alias Reason =
    { data : Comparison
    }


reason : Decoder Reason
reason =
    map Reason
        (field "data" comparison)


type alias Failure =
    { message : String
    , reason : Reason
    }


failure : Decoder Failure
failure =
    map2 Failure
        (field "message" string)
        (field "reason" reason)
```

**Comment by stil4m** [comment]
Could one of these options work for you?

```
type Reason = Reason Comparison

reason : Decoder Reason
reason =
    map Reason
        (field "data" comparison)

```

```
type alias Reason = Comparison

reason : Decoder Reason
reason =
        (field "data" comparison)
```

The second options is 'simpler' than the code you had before (losing a bit of the type-safety, but you do not have to call `.data` anymore. The first option adds the concept of an opaque type (which may be a good design decision based on your archictecture.

**Comment by mbuscemi** [comment]
Neither of those options compiles. In the first example, the compiler fails on `reason` because it can no longer find the `data` field to map to. In the second case, since `Reason` is an alias to `Comparison`, the `data` field is also missing, and this does not match the structure of the JSON.

If I were in control of the data source, I would simply adjust the data structure to avoid this problem, butas I mentioned, I am tied to the structure of data I am receiving from a third-party source.

Now, to be completely honest, I _could_ muck with the JSON structure in the JavaScript layer, but frankly, I would take this path only as an absolute last result (an elm-analyse error would not compel me down this road). It is one thing to have my Elm application be tightly coupled to third-party JSON structure (in Elm I have full type safety and immutability). It would be quite another to introduce structural coupling in the JS layer where no such protection exists.

Could not elm-analyse search the module in which a single-field type alias `X` appears for a function with the signature `Decoder X` and turn off the warning in this case? It seems to me as though there must be many contexts in which servers and other utilities, such as the one I am working with, return JSON with single fields at some levels.

**Comment by mbuscemi** [comment]
I've resolved this in code after some discussion. I was able to make your latter suggestion workable after rewriting some of the accessor functions to the data structure that resulted from the JSON decoding.
