### ISSUE TITLE
All Messages > Group By Type is broken?

### ISSUE THREAD

**Issue by jhrcek** [stil4m/elm-analyse#134]
Hello,
I love this tool! However in latest version (13.2) I noticed that grouping of messages by type doesn't work as expected. I'd expect the messages to be grouped by type, like first all "unused import" messages, then all "comment too long" etc. Is this expected behavior or a bug?

![screenshot](https://user-images.githubusercontent.com/2716069/34304955-542986c6-e73c-11e7-93c0-4983b0b8811f.png)

**Comment by stil4m** [comment]
Great to hear that you like it. Fixed this in `0.13.3`, which I will release later today.
It was a bug in the code that relied on a `toString` in combination with a `String.split`. Bad idea, you'll lose your type-safety... Sometimes I really suck. 

Thanks for reporting the bug. Much appreciated :)
