### ISSUE TITLE
Deprecated dependency: elm-css-frameworks

### ISSUE THREAD

**Issue by adeschamps** [stil4m/elm-analyse#147]
[elm-css-frameworks] is deprecated, although I don't think this will be much of a problem unless Bootstrap need to be updated.

[elm-css-frameworks]: http://package.elm-lang.org/packages/danielnarey/elm-css-frameworks/latest

**Comment by stil4m** [comment]
Good catch! I'll add the bootstrap source code to the public web resources and drop the dependency.
