### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by michaeljones** [stil4m/elm-analyse#152]
I have a code base with 33,000 lines of elm across 148 files (not including elm packages) and elm-analyse takes 43 seconds to process it all. I'm torn between thinking this is quite impressive and wondering if it could be faster. I'm curious if you have spent time working on performance aspects? 

I was curious to have a look to see if I could profile it though I'm not very experienced with this stuff. I wanted to ask first in case you had reason to believe it is already in an optimal state.

I feel like I would make use of it more if it was faster. Particularly if it reached a point where it could reasonably be integrated into my text editor. Though perhaps that is already possible? I haven't found evidence of vim support for it.

Thanks for the project. It has proven very useful and has helped catch & avoid several bugs during my time using it.

**Comment by stil4m** [comment]
Hi Michael,

I've looked into the performance while building the initial version of the parser. Things such as optimising some backtracking have been improved in those times. But I did not perform extensive benchmarks.

For improving the parser, please take a look at [elm-syntax](https://github.com/stil4m/elm-syntax).

Elm-analyse itself may benefit from threading. Files are currently loaded one-by-one. Optimising this may help.

In 0.13, I've been working on some editor integration, which allows editors such as Atom to connect to elm-analyse using a websocket. Once elm-analyse has been started, it will re-analyse only changed files and push the data on a websocket. Maybe this is something you are looking for?

**Comment by xtian** [comment]
Just wanted to chime in and say that elm-analyse has been very useful for the project I'm working on, but performance is also our main pain point.

Running the CLI script locally is not too bad, but we also run it on CI and it is one of the longer steps in that process (which handles both back-end and front-end code). Based on the logs it seems like most of the time spent is in loading files and dependencies.

**Comment by michaeljones** [comment]
I've spent a little time looking into this and sadly don't have that much to share but I think it is possible that clearing out the `elm-stuff/.elm-analyse/_shas` directory has improved the run time locally. Unfortunately I haven't been rigorous enough to know for sure but code runs `elm-format` on all the `*.elma` files in that directory and I imagine it is possible that that directory accumulates more and more `.elma` files over time? I believe that initial `elm-format` call has gone from 20 seconds down to 4.3 seconds after the clear out (and after a few more runs to re-establish the cache.)

I can't see that impacting CI runs due to the clean start though.

I do feel that the use of `elm-format` does have an impact and I'm wondering if it might be reasonable to have a way to disable that if the user is already consistently using `elm-format` in their own workflow? I assume it is used to produce more consistent checksums for caching. So that whitespace formatting changes don't produce a different checksum? I am not familiar enough with the code to really understand the use though so I am guessing.

**Comment by stil4m** [comment]
@michaeljones @xtian 

Sorry for my absence on this conversation.

There are two things in play here:

1) Based on the OS you are developing, you have different new line feeds. Running elm-format on a different OS than where the code was developed, elm-format will give a diff. And thus elm-analyse assumes that the code is not formatted properly. To fix this, all new lines are normalised, and the file content is stored under the hash of the original file (`abcdef0987654321.elma`). Elm format can run on the `.elma`, to check whether files ar formatted correctly or not (ignoring new lines). In addition the parsed files are stored there in JSON as well. 

2) Kind of the same thing happens for dependencies, although for each interface an abstract is saved in the home folder (`$HOME/.elm-analyse/<version>/interfaces/...`). Once a library has been indexed, it will not be re-indexed anymore.

 @xtian: I believe that caching this the `$HOME/.elm-analyse` folder on CI may give you an initial performance boost. I have not tested that out myself. You could try the same with `$PWD/elm-stuff/.elm-analyse`, but then you may encounter the issue that @michaeljones is running into.

@michaeljones Which version of `elm-format` are you running? I know that `0.7.0-exp` is much faster while being used in combination with `elm-analyse`.

---

I'm planning to do the following things:
  * Stop checking the format of files. `elm-format` will still be used when using the 'auto fix' functionality in the UI. I thought it was good to enforce people to use elm-format in combination with elm-analyse, but I think people would do that on their own.
 * Increase the speed of [elm-syntax](https://github.com/stil4m/elm-syntax)
 * Look into parallelisation. We probably have multiple cores, so why not use them.

**Comment by michaeljones** [comment]
Thanks for the breakdown. Interesting to see. I am using the `0.7.0-exp` version. I think any speed improvement would be a good thing but it is a difficult thing and I'm super impressed by the amount of work that has already gone in elm-analyse. It is certainly very useful!

**Comment by andys8** [comment]
I'm running `elm-analyse` on CI (Jenkins) on alpine linux on kubernetes. It takes around 12 minutes for `elm-analyse` with a clean working directory.

```sh
00:03:12.235 > elm-analyse
00:03:12.235 
00:03:12.647 Fetching package information from package.elm-lang.org.
00:03:13.203 Fetched dependencies
00:03:13.353 INFO: Load dependency cuducos/elm-format-number 6.0.0
00:03:14.004 INFO: Load dependency elm-lang/core 5.1.1
00:03:33.702 INFO: Load dependency elm-lang/navigation 2.1.0
00:03:36.238 INFO: Load dependency etaque/elm-transit 7.0.4
00:03:37.296 INFO: Load dependency etaque/elm-transit-style 3.1.0
00:03:37.967 INFO: Load dependency evancz/url-parser 2.0.1
00:03:40.314 INFO: Load dependency mgold/elm-date-format 1.6.0
00:03:43.477 INFO: Load dependency rtfeldman/elm-css 14.0.0
00:15:36.978 INFO: Load file src/Main.elm...
```

The execuction should already use `sysconfcpus -n 2`. So it would be interested if there is a way to improve the speed. It's not our main focus, but it could be that a single check or some dependency parsing is causing the majority of the execution time.

**Comment by stil4m** [comment]
@andys8. As you can see, `rtfeldman/elm-css` takes a long time to load. Could you mount a `$HOME/.elm-analyse/` into the container? Caching that, should resolve the most of your issues.

I'm looking into the possibilities to pre-calculate the dependency information needed for elm-analyse, and serve these via a CDN.

In addition, I've rewritten the parser (elm-syntax) for 0.19 and moved to the core parser library. There is a big speed improvement there since it is does not rely on backtracking anymore. This will be added in the next major release of elm-analyse.

**Comment by stil4m** [comment]
I've created an version of elm-analyse (`0.15.0-alpha.2`) in which the performance should be improved by 20-25%. In addition the formatting of files is not checked anymore (which speeds up the file analysis), and the dependency information is fetched from http://package.elm-lang.org/ (with fallback to the current local loading of dependencies for offline usage).

Can you verify the improvements?

```
npm install elm-analyse@0.15.0-alpha.2
```

@andys8 Could you verify this on your CI server?

**Comment by andys8** [comment]
I tested the new version **locally** (can't currently change the build related before) and removed the `.elm-analyse` before each run.

#### 0.14.2
`107.43user 1.16system 1:47.67elapsed 100%CPU`

#### 0.15.0-alpha.2
`90.73user 0.53system 1:30.96elapsed 100%CPU`

#### System
```
CPU: Intel Core i7-7600U CPU @ 3.9GHz
RAM: 3529MiB / 15930MiB
```

**Comment by stil4m** [comment]
Thanks Andy. That would be the ~20% gain. Coupe you do the same while removing the `~/.elm-analyse` folder?

**Comment by andys8** [comment]
As written, I removed the `.elm-analyse` folder in the home directory. Do you want me *not* to remove it?

**Comment by stil4m** [comment]
I read over that line. Thought the performance boost would be more significant, while elm-css is a big impact on the dependency loading stage (in 0.14.2).

Just to be sure. You ran it like this?

```
rm -rf ~/.elm-analyse
rm -rf elm-stuff
elm package install --yes
elm-analyse
```

**Comment by andys8** [comment]
Didn't remove `elm-stuff` before. Now looking even better. Added runs with cache, too.

#### 0.14.2

```shell
rm -rf ~/.elm-analyse/; rm -rf elm-stuff; npm i; time npm run lint
119.16user 1.22system 2:00.23elapsed 100%CPU

time npm run lint
3.08user 0.07system 0:04.66elapsed 67%CPU
```

#### 0.15.0-alpha.2

```shell
rm -rf ~/.elm-analyse/; rm -rf elm-stuff; npm i; time npm run lint
88.57user 0.56system 1:29.64elapsed 99%CPU

time npm run lint
1.24user 0.08system 0:02.02elapsed 65%CPU
```

**Comment by stil4m** [comment]
I'll close this for now. Gained a lot. In 0.16 there will be more performance gain through Elm `0.19`

**Comment by michaeljones** [comment]
Just run elm-analyse on our code base after a long hiatus and it is so much faster! Great job :) Thanks for all the hard work.
