### ISSUE TITLE
Is it possible to customize the analysis?

### ISSUE THREAD

**Issue by pietro909** [stil4m/elm-analyse#157]
I would like to introduce this tool in our validation pipeline, but there are a few rules which are too strict:

* no TODO in comments (unthinkable in a dev environment)
* no 100% exposure of a module (each module has a `Types.elm` file and everything inside it is to be consumed by its siblings)

In case the answer is "fork it", would you mind to give a hint of where the rules are defined?
Thanks! :-)

**Comment by pietro909** [comment]
Nevermind, just found https://stil4m.github.io/elm-analyse/#/configuration

Sorry!

**Comment by stil4m** [comment]
No problem :). If there is is anything else, just leave an issue or a message on Slack.
