### ISSUE TITLE
"Could not load file" when pattern matching on hex numbers

### ISSUE THREAD

**Issue by sporsh** [stil4m/elm-analyse#165]
Got
> Could not load file due to: Could not continue parsing on location

When running elm-analyse v0.14.2 on code that pattern matches on numbers using hex notation:

```elm
    case flag of
        0x01 ->
            "flag one"

        _ ->
            "unknown"
```

**Comment by stil4m** [comment]
Thanks for the report @sporsh. This is an issue in elm-syntax. I'll create an upstream ticket there.

**Comment by stil4m** [comment]
Fixed in version `5.X.X` of https://github.com/stil4m/elm-syntax
