### ISSUE TITLE
'Unknown Schema' issue when opening in web browser

### ISSUE THREAD

**Issue by brendanfh** [stil4m/elm-analyse#169]
I'm running into an issue where, upon visiting the website hosted locally at localhost:3000, I'm presented with this error:

```Something went wrong"I ran into a `fail` decoder at _.messages[1].data: Unknown schema"```

This only appears on the webpage. If I look in the terminal, or use the 'elm' extension for VSCode, it works just fine.

I'm running:
elm-analyse 0.15.0-alpha.3
elm 0.18.0

If you need more details, just let me know.

**Comment by stil4m** [comment]
Can you verify that it is not related to a browser cache issue?

**Comment by brendanfh** [comment]
Clearing all browser data seems to have worked. Thanks!
