### ISSUE TITLE
Incorrect generation of parent directory relative path

### ISSUE THREAD

**Issue by Steve-OH** [stil4m/elm-analyse#178]
[This problem occurs on Windows; I don't know if affects other OSes.]

I have the following `source-directories` array in my elm-package.json:
```json
    "source-directories": [
        "src/elm",
        "../../elmCommon"
    ],
```
elm-analyse incorrectly handles the path containing the `../` segments. For example, `src/elm/Foo.elm` is correctly parsed, but `../../elmCommon/Bar.elm` becomes `..\,..\elmCommon\Bar.elm`. Naturally, once the extraneous comma has been inserted, downstream code can't find the file.

I traced the problem to line 59 in file-gatherer.ts, which is:
```javascript
        const result = dirParts.map(() => '../').join() + sParts.join('/');
```
but ought to be:
```javascript
        const result = dirParts.map(() => '../').join('') + sParts.join('/');
```

I can generate a pull request if desired, but (a) it hardly seems worth it for such a small change, and (b) I'm having trouble building the project locally, so I can't run the tests.

**Comment by stil4m** [comment]
Hi Steve. Thank you for the report.
I've been busy with the Elm 0.19 upgrade. Once I finish that, I'll take this in for the new version.
