### ISSUE TITLE
Unused Import (& alias) check issue

### ISSUE THREAD

**Issue by roovo** [stil4m/elm-analyse#185]
Hi

I've found an issue where used imports and/or aliases are not being picked up.  Not sure the best terms I can use to describe it so here's an example from the tests to illustrate it.  I've just added ```.math``` in there (it's from Checks/UnusedImportAliasTests.elm):

```elm
usedAsQualified : ( String, String, List MessageData )
usedAsQualified =
    ( "usedAsQualified"
    , """module Foo exposing (..)

import Bar as B

foo = B.math.add 1

"""
    , []
    )
```

This test fails and I was expecting it to pass. It's the same for non-aliased imports too.  In my case I've got a Style module with a record in it containing colors I'm use in my app as in this truncated example:

```elm
import Page.Helper.Style as Style

icon : Element msg
icon =
    viewIcon Ionicon.loadC 32 (Element.toRgb Style.colors.text)

```

And it's highlighting this import as unused, which it isn't.

And many thanks for this library - it really is totally fab.  Cleaned a load of cruft out my project :)

**Comment by stil4m** [comment]
Thanks for the report @roovo. The problem actually lies within the parsing of `B.math.add` in `elm-syntax`. So i'll need to patch that.

Thanks for the great report though :).

**Comment by roovo** [comment]
thanks doode - very much appreciated - you're a ⭐️
