### ISSUE TITLE
Parsing error when function argument rec deconstruction is empty

### ISSUE THREAD

**Issue by shepelevstas** [stil4m/elm-analyse#238]
Hello! Thanks for the great tool! Superuseful!

```
foo : Point -> Point
foo ({} as p) = p
```
results in Parsing error, but happily compiles!

**Comment by jfmengels** [comment]
@shepelevstas This is rather an issue in `stil4m/elm-syntax`. Could you open an issue there instead?

**Comment by shepelevstas** [comment]
Done! =)

**Comment by jhf** [comment]
This was solved in ticket https://github.com/stil4m/elm-syntax/issues/42 that @shepelevstas reported, so when there is a new release of elm-analyse upgrading the dependency on elm-syntax this can be closed.
