### ISSUE TITLE
Use Cons Over Concat question

### ISSUE THREAD

**Issue by cbrake** [stil4m/elm-analyse#240]
I'm seeing the following. Is it valid to recommend using :: (cons) when the function argument is a list?

![image](https://user-images.githubusercontent.com/402813/81484721-02ac3f00-9216-11ea-8c6b-edf9f916f348.png)

**Comment by jfmengels** [comment]
@cbrake The rule is suggesting you to replace the code by the following:
```elm
  el (Element.htmlAttriute (Attr.class "markdown") :: styles ++ otherStyles
```

**Comment by cbrake** [comment]
@jfmengels thanks!
