### ISSUE TITLE
Cached sources interfere with code completion in elmjutsu

### ISSUE THREAD

**Issue by felixLam** [stil4m/elm-analyse#38]
When loading all files these appear to be cached in `elm-stuff/elm-analyse/` and in particular in `elm-stuff/elm-analyse/_shas`. This duplicates the source files, which confuses the popular Atom plugin [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu). Maybe we can find a way to store the cache outside of the source folder (e.g. in `/tmp` or `~/.elm-analyse`).

This issue manifests itself most prominently when also using the hyper click plugin.

**Comment by stil4m** [comment]
I will change the file extension from the cached files from `.elm` to something else (`.elma` for example).

I was thinking about making a global cache in the `$HOME` dir, but that might result in problems if you install `elm-analyse` in `node_modules` and use different versions in different projects. Maybe in the future :).

**Comment by felixLam** [comment]
The file extension should be fine. Maybe also change the folder name to be prefixed with a .

**Comment by stil4m** [comment]
Which folder to do mean?

**Comment by felixLam** [comment]
I added a comment here to clarify what I mean: https://github.com/stil4m/elm-analyse/commit/6a710349f32515ecdb1c006961982873d07ca6db
