### ISSUE TITLE
Apply fix does not work on Windows

### ISSUE THREAD

**Issue by pacbeckh** [stil4m/elm-analyse#4]
(node:8144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Trying to send an unexpected type of value through port `onFileContentWithShas`:
Expecting a String at _[0][0] but instead got: null

**Comment by stil4m** [comment]
@pacbeckh. Can you verify if this is still a problem?

**Comment by stil4m** [comment]
pacbeckh told me personally it seems to work.
