### ISSUE TITLE
Functions defined in let bindings

### ISSUE THREAD

**Issue by stil4m** [stil4m/elm-analyse#61]
`let` are commonly used to hold intermediate values that are used (multiple times) in other expressions in the `let` binding.

There is no reason to have functions in there, extracting these to top-levels would be a better choice. Encapsulation can be achieved by not exposing that extracted function or by creating a whole new module.

**Comment by felixLam** [comment]
I don't agree that this is an absolute. We have a few instances where there is a generic top level function and some othe functions calls this multiple times with only one differing argument. We then create a local alias that encapsulates the call along with the common arguments used in that function.

**Comment by felixLam** [comment]
But I can always switch that check off.

**Comment by stil4m** [comment]
I think there should be a distinction between curried function that become new functions and actually defining new functions.
In the following example I believe you do not want `bar` but `foo` is ok even though they are semantically equivalent.

```
foo x = 
   let 
     listModifier = List.map ((+) 1)
   in
     listModifier x

bar x = 
    let 
       incrementList y = List.map ((+) 1) y
    in
       incrementList x
```

**Comment by felixLam** [comment]
I believe both are OK as that might make sense for code readability or if the function "alias" is used more than once.

**Comment by stil4m** [comment]
This check will be disabled by default for now.
