### ISSUE TITLE
Append row and column number to filename.

### ISSUE THREAD

**Issue by Ruudieboy** [stil4m/elm-analyse#71]
Currently output looks like this:
```
Unused imported variable `form` in file "src/main/elm/Views/Dialogs/Maatschappij.elm" at ((8,32),(8,36))
```
It would be convenient if the format 
`filename:rownumber:colum` is supported. Most IDE's support directly opening the file and jumping to the matching row and column.

Example of prefered output.
```
Unused imported variable `form` in file "src/main/elm/Views/Dialogs/Maatschappij.elm:8:32" at ((8,32),(8,36))
```

**Comment by stil4m** [comment]
Good point. I'll look in to that.

Do you know any good resources that point out how you open a default application for a specific URL?

**Comment by Ruudieboy** [comment]
I couldn't find any documentation about this. It seems this works in most editors; I tested Atom, Sublime and Visual Studio Code.

**Comment by stil4m** [comment]
This will not be fixed. Direct editor integration is the way to go.
