### ISSUE TITLE
Elm-analyse processes files in elm-stuff/.elm-analyse

### ISSUE THREAD

**Issue by hakonrossebo** [stil4m/elm-analyse#83]
Verified that this occurs on Linux and Windows.

![image](https://user-images.githubusercontent.com/367175/27329146-db1a3ece-55b4-11e7-8094-77a623ba9068.png)

Seems to happen when I open a project with elm files in vscode

**Comment by stil4m** [comment]
Could you add the corresponding (anonymized) `elm-package.json`?

**Comment by hakonrossebo** [comment]
I'm actually testing against this project :) https://github.com/hakonrossebo/functional-programming-babelfish

**Comment by stil4m** [comment]
I (believe I) just fixed it in 0.9.2. Can you verify this?

**Comment by hakonrossebo** [comment]
Yes - seems to work as expected :)
