### ISSUE TITLE
Fixed messages not cleared when using websockets

### ISSUE THREAD

**Issue by hakonrossebo** [stil4m/elm-analyse#85]
When using websockets to receive messages in the vscode extension, messages are not beeing removed when doing a fix in the code that should remove this message.

I've testet this in the web interface, and the message is correctly removed.

Let me know if you need more details to reproduce.

**Comment by stil4m** [comment]
The web interface presents the data that is pushed on the websocket. Do you clear all the messages on the file before setting the new one (or replacing the messages)?

**Comment by hakonrossebo** [comment]
Yes, I'm also clearing messages each time I get the messages from websockets. I verified this, and I'm getting the same message item, when it should have been removed. Could this be a problem on my side with some websocket caching?

**Comment by stil4m** [comment]
There should be no caching on the WS. Can you go to the following steps:

* Find an message in VSCode.
* Fix it by hand
* Check if the message is removed in the web interface.

If the message is removed in the web interface there is probably something wrong in message handling in the plugin. If the message still exists in the browser version, can you check if the message correctly by opening it (clicking the id).

**Comment by hakonrossebo** [comment]
Yes, verified that the web interface always is correct when I remove/fix code. Somehow, this only happens on Windows - the reason can be that elm-analyse runs much slower on Windows - I'll test this more later.
