### ISSUE TITLE
Websocket messages - duplicates when saving a file

### ISSUE THREAD

**Issue by hakonrossebo** [stil4m/elm-analyse#88]
This is related to my vscode-elm PR https://github.com/Krzysztof-Cieslak/vscode-elm/pull/145
Using this as a test project: https://github.com/hakonrossebo/functional-programming-babelfish

At first, when I activate the elm-analyse, I get this in the console when started:
![image](https://user-images.githubusercontent.com/367175/27421873-79eca708-572c-11e7-8a5b-712c27b93c4b.png)

When performing a line delete and saving any file, elm-analyse responds by doubling/duplicating the original messages for this file. Example: I open CustomPorts.elm, delete a line and save, I get this in the output: 
![image](https://user-images.githubusercontent.com/367175/27422029-0e9d0348-572d-11e7-9252-f51567044a2e.png)
This is also reflected in the problems list:
![image](https://user-images.githubusercontent.com/367175/27422112-5527eff8-572d-11e7-9bfd-3e909d8c5555.png)

Note: the output also shows that each file save generates two "Load file" events - this also results in 2 websocket message events (I'm clearing my issue collection each time) - But I don't think this is related to the duplicates.

**Comment by stil4m** [comment]
Thanks for opening the issue. Can you add the commit ID that I can use to reproduce it?

**Comment by hakonrossebo** [comment]
It's the latest commit for both, but for future changes, the current commit id's are:
https://github.com/Krzysztof-Cieslak/vscode-elm/pull/145/commits/5717457ca2965383727925fa44355175a915cf10

and
https://github.com/hakonrossebo/functional-programming-babelfish/commit/3ed195eaa0fb82b1e55ede381ab863b87aca9ac6

**Comment by hakonrossebo** [comment]
Now, I've tested and verified that this doubling of messages also happens when I run elm-analyse as a separate terminal process, and editing the same file in vim.
![image](https://user-images.githubusercontent.com/367175/27423699-bfc22900-5732-11e7-8fb0-a2e0cf9a7923.png)

**Comment by stil4m** [comment]
Seems like a bug in elm-analyse. Seems that the file is reloaded twice :/. Can you reproduce it with another file?

**Comment by hakonrossebo** [comment]
Yes, any file in this project - 
![image](https://user-images.githubusercontent.com/367175/27423828-42c6204a-5733-11e7-8150-6cd6a305f743.png)

**Comment by hakonrossebo** [comment]
Also verified the same on another project.

**Comment by stil4m** [comment]
The problem is in the watcher, which takes all source directories specified in `elm-package.json`.
The watcher is triggered twice on a change because every source file matches either `.` and `./src`. The easy fix for you is to change `source-directories` in `elm-package.json` to:

```
...
    "source-directories": [
        "./src"
    ],
...
```

**Comment by hakonrossebo** [comment]
Thanks - this will help :)

**Comment by hakonrossebo** [comment]
Switched back to Windows now. While working ok on Linux, I'm now getting a double set of messages for the file I'm saving. Verified on two projects, only one source directory in elm-package.json

**Comment by stil4m** [comment]
Will try this out when I have time: `https://github.com/yuanchuan/node-watch/issues/46`. Could fix it. The current problem lies in the lib. If it doesn't work I change the watcher library.

**Comment by hakonrossebo** [comment]
Ok. For editor integration - If this can help - It's also possible to have the editor notify elm-analyse on any file changes.

**Comment by stil4m** [comment]
Yes this would be possible. The problem I have with this, is that then every editor integration has to correctly implement this, probably running in the same bugs we are finding now.

It is a good idea though. A future option may be to disable file watchers in `elm-analyse` with a flag, and allow changes to be pushed through the socket. And this is likely where we end up using the Language Server Protocol.

**Comment by stil4m** [comment]
@hakonrossebo Could you try if you can reproduce the issue using the just released 0.9.3?

**Comment by hakonrossebo** [comment]
I verified on Windows now - seems to work fine :)
